version: 2

models:
   - name: customers
     description: "This table has basic information about a customer, as well as some derived facts based on a customer's orders"
     columns:
       - name: CustomerID
         description: "This is a unique identifier for a customer"
         tests:
          - unique
          - not_null
       - name: FirstName
         description: "Customer's first name. PII."
       - name: LastName
         description: "Customer's last name. PII."
       - name: Email
         description: "Customer's Email."
       - name: Phone
         description: "Customer's Phone number."
       - name: Address
         description: "Customer's Address."
       - name: City
         description: "Customer's City."

         